### ISSUE TITLE
Adicionar modo sem paginação para componente de tabela.

### ISSUE THREAD

**Issue by MatheusCSG** [siga-fab/cca-fab-components#41]

**Comment by santanarscs** [comment]
Fala ai @luizmariz, nao seria mais interessante em adicionar um componente de paginação e outro de tabela ?

**Comment by luizmariz** [comment]
> Fala ai @luizmariz, nao seria mais interessante em adicionar um componente de paginação e outro de tabela ?

É uma boa ideia. Pode existir outro componente com essa finalidade sim. Algo bem simples e genérico (não necesssariamente exatamente igual o da tabela atual) para o uso em qualquer layout.

Vou adicionar no backlog como uma nota :)

**Comment by luizmariz** [comment]
A tabela agora recebe a prop `paginated`. Caso false a paginação não será renderizada. Próxima release já vai vir com essa alteração.
