### ISSUE TITLE
Componente autocomplete

### ISSUE THREAD

**Issue by santanarscs** [siga-fab/cca-fab-components#61]
Não foi carregado a doc automatica do componente de autocomplete, tenho também algumas dúvidas:

1. o evento de "confirmed" retorna um array? Se sim, ele retorna sempre um array com uma posição e é sempre uma string? seria viável trocar o retorno para apenas uma string?

2. o evento changed é emitido a cada alteração no campo sem existir um debounce para diminuir a quantidade de requisição, se os dados forem carregados de uma lista estatica acho q nao tem problema, mas se for carregado de uma api, acho q seria interessante adicionar um debounce de 3 segundos mais ou menos para uma nova requisição.

Caso seja de interesse da equipe essas alterações eu gostaria de abrir uma PR para fazer

**Comment by MatheusCSG** [comment]
> Não foi carregado a doc automatica do componente de autocomplete

Esse componente (e mais alguns) não estão referenciados no **default** dos seus respectivos Stories, já que o add-on de documentação tinha sido removido previamente. Como no momento a documentação não é prioridade, isso está sem segundo plano para ser feito adequadamente num momento mais oportuno. Apesar disso, se o interesse for apenas permitir que eles carreguem no compodoc é só adicionar 1 linha no **export default** de cada Story.

![image](https://user-images.githubusercontent.com/66928978/96882694-f29bbb00-1455-11eb-9379-d3940489e0f2.png)

> 1. o evento de "confirmed" retorna um array? Se sim, ele retorna sempre um array com uma posição e é sempre uma string? seria viável trocar o retorno para apenas uma string?

Não, ele pode retornar uma string ou um **SelectOption**, que é um tipo simples, feito para a library, que consiste num objeto com o seguinte formato:

`{ name: string, value: any }`

É usado por ele e pelo componente de **Select**, e também é exportado para ser usado.

**Comment by MatheusCSG** [comment]
Opa, bom dia!

> Não foi carregado a doc automatica do componente de autocomplete

Esse componente (e mais alguns) não estão referenciados no **default** dos seus respectivos Stories, já que o add-on de documentação tinha sido removido previamente. Como no momento a documentação não é prioridade, isso está sem segundo plano para ser feito adequadamente num momento mais oportuno. Apesar disso, se o interesse for apenas permitir que eles carreguem no compodoc é só adicionar 1 linha no **export default** de cada Story.

![image](https://user-images.githubusercontent.com/66928978/96882694-f29bbb00-1455-11eb-9379-d3940489e0f2.png)

> 1. o evento de "confirmed" retorna um array? Se sim, ele retorna sempre um array com uma posição e é sempre uma string? seria viável trocar o retorno para apenas uma string?

Não, ele pode retornar uma string ou um **SelectOption**, que é um tipo simples, feito para a library, que consiste num objeto com o seguinte formato:

`{ name: string, value: any }`

É usado por ele e pelo componente de **Select**, e também é exportado para ser usado. Não acho que o ideal seja trocar o retorno apenas pela string, acredito que seria uma boa a saída ser sempre o tipo **SelectOption,** já que dá mais liberdade ao usuário na hora da implementação, de permitir que o valor mostrado esteja associado a um valor mais significativo, como o ID de uma entidade do banco, por exemplo.

> 2. o evento changed é emitido a cada alteração no campo sem existir um debounce para diminuir a quantidade de requisição, se os dados forem carregados de uma lista estatica acho q nao tem problema, mas se for carregado de uma api, acho q seria interessante adicionar um debounce de 3 segundos mais ou menos para uma nova requisição.

A ideia é que os componentes, no geral, se aproximem mais do conceito de "presentational components" (um nome desnecessariamente "elegante" para a ideia de delegar a menor quantidade de responsabilidade e lógica possível para que um componente seja genérico e se preocupe só com aspectos mais fundamentais do seu funcionamento). A ideia é que para implementar o debounce, quando for necessário, o desenvolvedor se utilize de artifícios que o Angular já proporciona, através do Reactive Forms e do RxJS, da seguinte maneira:

![image](https://user-images.githubusercontent.com/66928978/96884881-650d9a80-1458-11eb-8929-148cc474c5fb.png)

Tem um exemplo disponível [aqui](https://github.com/siga-fab/siga-planejamento-fe/blob/fe1dd884052610d8fd02c60a1f37bef6e46eb0e5/src/app/components/arvore-components/arvore-autocomplete/arvore-autocomplete.component.ts#L25).

**Comment by santanarscs** [comment]
Boa @MatheusCSG excelente o retorno, eu nao olhei o codigo e nao me atentei ao tipo select q é exportado, foi também uma ótima decisão deixar a responsabilidade do debounce no componente que irá usar o autocomplete👏 mandou muito bem!

Infelizmente a doc nao esta OK, mas vamos em frente

**Comment by luizmariz** [comment]
@santanarscs adicionei ao menos a prop table nos componentes que faltavam
